### ISSUE TITLE
Remove variable nodes in graph.

### ISSUE THREAD

**Issue by AdiHarif** [Ortal1993/compilation-project#1]
As variables are a source code "creature", we dont need them in our IR.
Removing variable nodes will make our graphs simpler and easier to analyze.

Note that this does not include function parameters, these are still needed.

**Comment by ronynudelman** [comment]
Done
[commit](https://github.com/Ortal1993/compilation-project/commit/e3af6e56ca4b3ec112c6a2c392374a6a845783b7)

**Comment by AdiHarif** [comment]
Great, thanks!
